# Generated by Django 4.2.6 on 2023-10-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date published')),
                ('author', models.CharField(max_length=200)),
                ('ticket', models.CharField(max_length=200)),
                ('ticket_comment', models.TextField()),
                ('priority', models.CharField(max_length=200)),
                ('status', models.CharField(max_length=200)),
                ('executor', models.CharField(max_length=200)),
                ('deadline', models.CharField(max_length=200)),
            ],
        ),
    ]
