# Generated by Django 4.2.6 on 2024-02-15 21:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0007_alter_fileattachment_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChecklistTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('items', models.TextField(verbose_name='Элементы')),
            ],
            options={
                'verbose_name': 'Шаблон чеклиста',
                'verbose_name_plural': 'Шаблоны чеклистов',
            },
        ),
        migrations.AlterModelOptions(
            name='fileattachment',
            options={'ordering': ['-id'], 'verbose_name': 'Файлы', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.AlterField(
            model_name='fileattachment',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='task.task', verbose_name='Задача'),
        ),
        migrations.AddField(
            model_name='task',
            name='checklist_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='task.checklisttemplate', verbose_name='Шаблон чеклиста'),
        ),
    ]
