# Generated by Django 4.2.6 on 2024-02-15 22:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0012_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='executor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[(1, 'Низкий'), (2, 'Средний'), (3, 'Высокий'), (4, 'Очень высокий'), (5, 'Критический')], default='1', max_length=200, verbose_name='Приоритет'),
        ),
    ]
