# Generated by Django 4.2.6 on 2024-02-16 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_alter_task_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Дедлайн'),
        ),
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.CharField(choices=[('low', 'Низкий'), ('medium', 'Средний'), ('high', 'Высокий'), ('very_high', 'Очень высокий'), ('critical', 'Критический')], default='low', max_length=200, verbose_name='Приоритет'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('in_progress', 'В работе'), ('completed', 'Завершено'), ('postponed', 'Отложено'), ('canceled', 'Отменено'), ('pending', 'В ожидании'), ('planned', 'В планах'), ('under_review', 'На проверке'), ('under_revision', 'На доработке'), ('under_approval', 'На утверждении'), ('under_consideration', 'На согласовании')], default='1', max_length=200, verbose_name='Статус'),
        ),
    ]
