# Generated by Django 4.2.6 on 2024-02-17 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0019_checklistitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklistitem',
            name='status',
        ),
        migrations.AlterField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ticket',
            field=models.CharField(max_length=200, verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='task',
            name='ticket_comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к задаче'),
        ),
        migrations.CreateModel(
            name='ChecklistItemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task.checklistitem')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklist_statuses', to='task.task')),
            ],
            options={
                'verbose_name': 'Статус элемента чеклиста',
                'verbose_name_plural': 'Статусы элементов чеклиста',
            },
        ),
    ]
