# Generated by Django 4.2.6 on 2024-02-18 01:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('task', '0021_alter_checklistitemstatus_is_completed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskstatus',
            options={'ordering': ['-id'], 'verbose_name': 'Статус задачи', 'verbose_name_plural': 'Статусы задачи'},
        ),
        migrations.AddField(
            model_name='taskstatus',
            name='executor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='executor_statuses', to=settings.AUTH_USER_MODEL, verbose_name='Исполнитель'),
        ),
    ]
