# Generated by Django 4.2.6 on 2024-02-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0017_alter_task_author'),
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
