# Generated by Django 4.2.6 on 2023-11-08 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_comment_options_alter_task_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileattachment',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
