# Generated by Django 4.2.6 on 2023-11-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_fileattachment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='description',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание'),
        ),
    ]
