# Generated by Django 4.2.6 on 2024-02-15 20:49

from django.db import migrations, models
import task.models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0006_alter_fileattachment_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileattachment',
            name='file',
            field=models.FileField(upload_to=task.models.FileAttachment.get_upload_path, verbose_name='Файл'),
        ),
    ]
