# Generated by Django 4.2.6 on 2024-02-15 22:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0009_alter_checklisttemplate_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checklisttemplate',
            name='items',
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Элемент')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='task.checklisttemplate')),
            ],
            options={
                'verbose_name': 'Элемент чеклиста',
                'verbose_name_plural': 'Элементы чеклиста',
            },
        ),
    ]
