# Generated by Django 4.2.6 on 2024-02-17 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0018_alter_task_deadline_alter_task_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checklistitem',
            name='status',
            field=models.BooleanField(default=False, verbose_name='Готово'),
        ),
    ]
