# Generated by Django 4.2.6 on 2024-02-18 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0023_alter_taskstatus_executor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskstatus',
            name='status',
            field=models.CharField(choices=[('created', 'Создано'), ('in_progress', 'В работе'), ('completed', 'Завершено'), ('postponed', 'Отложено'), ('canceled', 'Отменено'), ('pending', 'В ожидании'), ('planned', 'В планах'), ('under_review', 'На проверке'), ('under_revision', 'На доработке'), ('under_approval', 'На утверждении'), ('under_consideration', 'На согласовании')], max_length=200, verbose_name='Статус'),
        ),
    ]
